services:

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes

    ports:
      - 2181:2181
    networks:
      yt-network:
        aliases:
          - zookeeper

  yt-kafka:
    container_name: yt-kafka
    image: bitnami/kafka:3.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    healthcheck:
      test: [ 'CMD', 'kafka-topics', '--bootstrap-server', '--version' ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      yt-network:
        aliases:
          - kafka
networks:
  yt-network: